name: Events Workflow Demo

on:
<<<<<<< HEAD

  push:
    branches:
      - main
=======
  workflow_dispatch:
>>>>>>> 2371ec8 (matrix strategy)
jobs:
  demo-repo-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: test-Events
        run: |
          echo "Hello World"
  demo-concurrency:
    runs-on: ubuntu-latest
    concurrency:
      group: "demo-repo-secrets"
      cancel-in-progress: true

    steps:
      - name: test-concurrency
        run: |
          sleep 90s
          echo "Hello concurrency"
