name: Events Workflow Demo

on:

  push:
    branches:
      - main
jobs:
  demo-repo-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: test-Events
        run: |
          echo "Hello World"
