name: Filters and Events Demo
on:
  push:
    branches:
      - main
      - "releases/**"

  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3

      - name: Print Event Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"

      - name: Run Only on Push
        if: github.event_name == 'push'
        run: echo "This step runs only on push events"

      - name: Run Only on Pull Request
        if: github.event_name == 'pull_request'
        run: echo "This step runs only on PR events"

      - name: Run Only on Schedule
        if: github.event_name == 'schedule'
        run: echo "This step runs only on scheduled events"

      - name: Run Only on Manual Trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "This step runs only on manual trigger"
          echo "Selected environment: ${{ github.event.inputs.environment }}"
