name: CID

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, GitHub Actions!"

      - name: Run a multi-line script
        run: |
          echo "Starting multi-line script"
          echo "Line 1"
          echo "Line 2"
          echo "Script completed"
