name: Generate ASCII Art
on:
  # push:
  #   branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-script
        run: |
          chmod +x script.sh
          ./script.sh
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ascii_art.txt
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: test-command
        run: |
          echo "Hello World"
          python --version
          ls -al
          pwd
          cat ascii_art.txt
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: deploy-command
        run: |
          echo "Deploying"
          grep "GitHub" ascii_art.txt
