name: Repository Variables and Secrets Demo

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  demo-repo-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Demo Repository Variables
        run: |
          echo "Repository Variable: ${{ vars.USER }}"

      - name: Demo Repository Secrets
        env:
          SECRET_KEY: ${{ secrets.PASSWORD }}
        run: |
          if [ -n "$SECRET_KEY" ]; then
            echo "Repository secret is set and available"
            # Don't echo the actual secret value for security
          else
            echo "Repository secret is not set"
          fi
